---
- name: install app dependencies
  apt: name={{ item }} state=latest
  become: yes
  with_items:
    - git
    - nodejs

- name: link nodejs
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
  become: yes

- name: create source directory
  become: yes
  file:
    path: "{{ app_path }}"
    state: directory
    mode: 0755
    owner: "{{ app_user }}"
    group: www-data
    recurse: yes

- name: clone or update source
  git:
    repo: "{{ git_url }}"
    version: "{{ git_branch }}"
    dest: "{{ app_path }}"
    update: yes
    accept_hostkey: yes
    force: yes

- name: export rails env variables
  template: src=rails_env.sh.j2 dest=/etc/profile.d/rails_env.sh mode=0644
  become: yes

- name: export db settings
  template: src=database.yml.j2 dest="{{ app_path }}/config/database.yml" mode=0644

- name: save ruby path for application
  shell: "`which passenger-config` --ruby-command | grep -e Command | sed -n -e 's/^.*Command: //p'"
  args:
    chdir: "{{ app_path }}"
  register: ruby_path

- name: install dependencies
  bundler: state=present chdir="{{ app_path }}"
  register: rails_build

- name: precompile assets
  shell: "bundle exec rails assets:clean assets:precompile"
  args:
    chdir: "{{ app_path }}"
  register: rails_build

- name: migrate database
  shell: ". /etc/profile.d/rails_env.sh && bundle exec rails db:migrate"
  args:
    chdir: "{{ app_path }}"
  register: rails_build
