---
- name: update apt-get
  apt: update_cache=yes cache_valid_time=300

- name: install required software
  apt: name={{ item }} state=latest
  with_items:
    - curl

- name: set up authorized_keys for the root user
  authorized_key: user=root key="{{ item }}" state=present
  with_file:
    - public_keys/id_rsa.pub
  notify: restart ssh

- name: disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: restart ssh

- name: set default PWD
  lineinfile: dest="/root/.bashrc" line="cd {{ app_path }}"
