---
- name: install db dependencies
  apt: name="{{ item }}" state=latest
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2

- name: Start PostgreSQL and enable at boot
  service: name=postgresql enabled=yes state=started

- name: initialize app databases
  become: yes
  become_user: postgres
  become_method: su
  postgresql_db: name="{{ item }}" port="{{ db_rails_port }}" encoding="UTF-8" login_user=postgres
  with_items:
    - "{{ db_rails_name }}_dev"
    - "{{ db_rails_name }}_test"
    - "{{ db_rails_name }}"
  notify: restart db

- name: initialize db users
  become: yes
  become_user: postgres
  become_method: su
  postgresql_user:
    name: "{{ db_rails_username }}"
    password: "{{ db_rails_password }}"
    role_attr_flags: CREATEDB,NOSUPERUSER
    state: present
    login_user: postgres
  notify: restart db
