---
- name: apply common configuration to all nodes
  hosts: all
  remote_user: root
  roles:
    - common

- name: deploy and configure rvm
  hosts: web_servers
  remote_user: root
  roles:
    - rvm_io.rvm1-ruby
    - abtris.nginx-passenger

- name: install the db
  hosts: db_servers
  remote_user: "{{ app_user }}"
  roles:
    - db_setup

- name: install the rails app
  hosts: web_servers
  remote_user: "{{ app_user }}"
  roles:
    - app_setup

- name: run the rails app
  hosts: web_servers
  remote_user: "{{ app_user }}"
  become: yes
  roles:
    - app_web_server
