---
rails_env: production
secret_key_base: "{{ vaulted_secret_key_base }}"

main_db_server: 159.203.29.210
main_web_server: 159.203.46.230

server_name: "{{ main_web_server }}"

db_rails_username: rails
db_rails_password: "{{ vaulted_db_rails_password }}"
db_rails_port: 5432
db_rails_name: workshop_app
